### ISSUE TITLE
JRI 2.5.0 Errors

### ISSUE THREAD

**Issue by jfernal** [daust/JasperReportsIntegration#10] opened 2018-09-29 20:47 UTC
I was trying test JRI 2.5.0 and I have some errors.
**1) Apex application, error installing on APEX 18.2**
**2) Error compiling user package XLIB_JASPERREPORTS (line 237 and 353)**
  `l_url := l_url || '&_printJobName=' || bool2string(p_print_job_name);`
**3) Error running "test" report on APEX application, report runs showing a binary page.** 

**Note: Yes, please, upgrade to 6.7.0 libraries.**
![image](https://user-images.githubusercontent.com/8763264/46250816-9e55b680-c408-11e8-8a63-ffc25e7e7b07.png)

**Comment by daust** [comment] 2018-09-30 06:47
1) Well, here we are actually hitting a bug (I guess due to the older compatibility mode setting in the app) https://community.oracle.com/thread/4173070. The workaround is simple, just install on the command line using sqlplus . You will probably want to change your environment in the session prior to installing the script: 

```sql
SQL> DECLARE
  2     l_workspace_id   NUMBER;
  3  BEGIN
  4     l_workspace_id := APEX_UTIL.FIND_SECURITY_GROUP_ID ('JRI_TEST');
  5     apex_application_install.set_workspace_id (l_workspace_id);
  6     apex_application_install.generate_application_id;
  7     apex_application_install.set_schema('JRI_TEST');
  8  END;
  9  /

PL/SQL procedure successfully completed.

SQL> @f121_JasperReportsIntegration-Test_2.5.0.0.sql
```
For the next fix 2.5.0.1 I will make a version available which installs into 18.1 without problems.

2) This is weird, it did compile during my testing. Anyhow this is wrong, I already fixed it in dev. 

Just change the line
```
l_url := l_url || '&_printJobName=' || bool2string(p_print_job_name);
```
to
```
l_url := l_url || '&_printJobName=' || p_print_job_name;
```

conversion to bool is not required here ... copy / paste mistake. 

3) this one I cannot reproduce. please make the above changes and try again. 

4) Good catch, I will check. The funny thing is that the JasperReports team did make a mistake here. I am calling their .getVersion() function and I have deployed the latest libraries, but they still return version 6.6.0: 

![greenshot 2018-09-30 08 44 14](https://user-images.githubusercontent.com/4840057/46254282-2e3d4400-c48d-11e8-887d-1375d3929509.png)

**Comment by daust** [comment] 2018-09-30 11:32
I have just released a fix here https://github.com/daust/JasperReportsIntegration/releases/tag/v2.5.0.1 and also included a few more fixed bugs.

**Comment by jfernal** [comment] 2018-09-30 16:45
Woooh.!!!  Thanks @daust ...!! You are a great person.!! 
Regards @jfernal

**Comment by daust** [comment] 2020-09-14 13:17
Closing the issue. Cleaning up the older tickets.

**Closed by daust** 2020-09-14 13:17 UTC
