### ISSUE TITLE
Error executing report with Oracle datalink first time only

### ISSUE THREAD

**Issue by nlwilson02** [daust/JasperReportsIntegration#73] opened 2021-03-11 17:09 UTC
We just upgraded to use the new jri.war (2.7). Every morning the first time a report is executed that uses database links it gets an error.  A reload of the page and the report runs successfully.  We have been using the same code for years without issue so I am thinking I am missing some configuration parameter.  We are using Apache Tomcat, Oracle 19c.  

Type Exception Report

Message Error executing SQL statement for: HR_WAGE_REMINDERS.

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.RuntimeException: Error executing SQL statement for: HR_WAGE_REMINDERS.
	de.oc.utils.Utils.throwRuntimeException(Utils.java:18)
	de.oc.integration.jasper.webapp.ReportWrapper.service(ReportWrapper.java:265)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
Note The full stack trace of the root cause is available in the server logs.

**Comment by nlwilson02** [comment] 2021-03-11 20:22
Also seeing this warning in the catalina.out file
log4j:WARN No appenders could be found for logger (de.oc.integration.jasper.webapp.AppServletContextListener).

**Comment by daust** [comment] 2021-03-17 16:58
Just to confirm: 
- did anything else change or just the change in jri - exchanging the JasperReportsIntegration? Could you perhaps reproduce with the previous version that it still works?
- Do you get an Oracle SQL Error? 

Could you please increase the log level as described here: https://github.com/daust/JasperReportsIntegration#faq

Once we have an Oracle error, we can go deeper. Cheers.

**Comment by nlwilson02** [comment] 2021-03-18 11:53
The only change was to upgrade to use the new jri.war.  I found that I haven’t fully upgraded to the latest version 6.16 and was experiencing the bug in version 6.15, random HTTP 500 errors.  After completing the upgrade to 6.16 we are no longer seeing the intermittent HTTP error’s but I still see the below warning in the Tomcat catalina.out log file.  Does this indicate we are missing a configuration step ?

log4j:WARN No appenders could be found for logger (de.oc.integration.jasper.webapp.AppServletContextListener).
log4j:WARN Please initialize the log4j system properly.


Thanks you so much for your time and providing this extremely useful and invaluable integration tool for Oracle Apex and JasperReports!

**Comment by daust** [comment] 2021-03-18 17:20
This is good news!

The message
```
log4j:WARN No appenders could be found for logger (de.oc.integration.jasper.webapp.AppServletContextListener).
log4j:WARN Please initialize the log4j system properly.
```
This is typically due to missing configuration files. 

You need the ``log4j.properties`` file in the configuration directory. 
![image](https://user-images.githubusercontent.com/4840057/111668741-5912e280-8816-11eb-8dd0-e1d4f74ee1fc.png)

You can check the different locations on the homepage of the ``jri.war`` file: 
![image](https://user-images.githubusercontent.com/4840057/111668854-7e075580-8816-11eb-9938-0a57f76906ea.png)

It doesn't cause any issues ... but it is better to have it in the right location, will get rid of the messages.

**Comment by nlwilson02** [comment] 2021-03-18 18:06
The file log4j.properties exists in the /opt/jri/conf directory, which is where all the configuration and reports reside.    Do I have to use JasperReportsIntegration as the folder name, my OC_JASPER_CONFIG_HOME environment variable is set to /opt/jri


***@***.***D71BFF.68AC4610]

**Comment by daust** [comment] 2021-03-22 09:35
```
Do I have to use JasperReportsIntegration as the folder name, my OC_JASPER_CONFIG_HOME environment variable is set to /opt/jri
```
That sounds correct. 
Can you please post the configuration info section from the J2EE homepage http://host:port/jri as I did before. Then I can see the relevant configuration parts. 

Thank you.

**Comment by daust** [comment] 2022-02-08 14:58
Are you still experiencing these issues? 
Else I will close the issue in a few days. Thank you.

**Comment by daust** [comment] 2022-02-28 15:22
Perfect! Sounds great. 
You are more than welcome :). Thank you.

**Closed by daust** 2022-02-28 15:22 UTC
Labels: waiting for reply from reporter
